spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always   # 起動時にSQLを実行

resilience4j:
  circuitbreaker:
    instances:
      IssCircuitBreaker:
        registerHealthIndicator: true # ヘルスチェックを有効にする
        slidingWindowSize: 10 # スライディングウィンドウのサイズ。10回の呼び出しを記録する。
        minimumNumberOfCalls: 5 # サーキットブレーカーが開くために必要な最小の呼び出し回数
        failureRateThreshold: 50 # サーキットブレーカーが開くために必要な失敗率
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3 # サーキットブレーカーが半開いている間に許可される呼び出し回数
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException$TooManyRequests
          - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError
          - org.springframework.web.reactive.function.client.WebClientResponseException$BadGateway
          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
          - org.springframework.web.reactive.function.client.WebClientResponseException$GatewayTimeout
        ignoreExceptions: []

  retry:
    instances:
      IssRetry:
        maxAttempts: 3
        waitDuration: 1000ms
        exponentialBackoffMultiplier: 2.0
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException$TooManyRequests
          - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError
          - org.springframework.web.reactive.function.client.WebClientResponseException$BadGateway
          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
          - org.springframework.web.reactive.function.client.WebClientResponseException$GatewayTimeout
        ignoreExceptions: []

